version: "3.9"

services:
  selenium-hub:
    image: selenium/hub:4.25.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  chrome-node:
    image: selenium/node-chrome:4.25.0
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
    shm_size: 2gb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://selenium-hub:4444/status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      chrome-node:
        condition: service_healthy
    env_file: ".env"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${APP_PORT}/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_OUTER_PORT}:${POSTGRES_INNER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c port=${POSTGRES_INNER_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_INNER_PORT}"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local