from typing import Protocol, List
from uuid import UUID
from app.domain.models.balance import Balance

class IBalanceRepository(Protocol):
    async def add(self, balance: Balance) -> None: ...
    async def remove(self, balance_id: UUID) -> None: ...
    async def get_all(self) -> List[Balance]: ...
    async def get_by_id(self, balance_id: UUID) -> Balance | None: ...
