version: "3.8"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_OUTER_PORT}:${POSTGRES_INNER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c port=${POSTGRES_INNER_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_INNER_PORT}"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  dolbabot:
    build: .
    container_name: dolbabot
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: [ "CMD", "pgrep", "-f", "main.py" ]
      interval: 15s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    driver: local